version: '3'

services:
  mongo_app:
    image: mongo
    container_name: mongo_app
    ports:
        - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db

  notebook:
    build: .
    container_name: notebook_app
    ports:
     - "8888:8888"
    command: ["pipenv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    volumes:
      - ./:/home/dev/code/

  mongo_feed:
    build: ./mongo_feed
    container_name: mongo_feed_app
    depends_on:
      - mongo_app
    volumes:
      - ./app/mongo_data:/home/data
      - ./scrapy_folder:/home/scrapy_folder

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: projet_image
    container_name: app
    restart: always
    ports:
      - "8050:8050"
    depends_on: 
      - mongo_app
      - mongo_feed
    volumes:
      - ./app:/home/app
      - ./scrapy_folder:/home/scrapy_folder
    environment:
      FLASK_ENV: development