version: '3'

services:
  mongo_app:
    image: mongo
    ports:
        - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db

  notebook:
    build: .
    ports:
     - "8888:8888"
    command: ["pipenv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    volumes:
      - ./:/home/dev/code/

  mongo-seed:
    build: ./mongo
    depends_on:
      - mongo_app

  flask:
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: projet_image
    container_name: app
    restart: always
    ports:
      - "8050:8050"
    depends_on: 
      - mongo_app
    volumes:
      - ./app:/home/flask
    environment:
      FLASK_ENV: development